# Generated by Django 3.2.3 on 2021-05-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elevator',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='elevatorq',
            options={'ordering': ['create_time']},
        ),
        migrations.AlterModelOptions(
            name='pressbtnq',
            options={'ordering': ['create_time']},
        ),
        migrations.AddIndex(
            model_name='elevatorq',
            index=models.Index(fields=['elevator', 'create_time'], name='elevatorq_e_elevato_6e57f4_idx'),
        ),
    ]
