# Generated by Django 3.2.3 on 2021-05-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorq', '0003_auto_20210521_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingelevator',
            name='algo',
            field=models.CharField(default='elevatorq.look', max_length=100),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='current_floor',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='range_max_floor',
            field=models.SmallIntegerField(default=47),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='range_min_floor',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='set_lobby_floor',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='speed_close',
            field=models.DecimalField(decimal_places=2, default=3.7, max_digits=2),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='speed_floor',
            field=models.DecimalField(decimal_places=2, default=2.1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='speed_open',
            field=models.DecimalField(decimal_places=2, default=8.4, max_digits=2),
        ),
    ]
