# Generated by Django 3.2.3 on 2021-05-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorq', '0004_auto_20210521_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingelevator',
            name='algo',
            field=models.CharField(default='elevatorq.look', help_text='extra - support different algorithm by building elevator', max_length=100),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='name',
            field=models.CharField(help_text='Elevator unique name', max_length=10),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='range_max_floor',
            field=models.SmallIntegerField(default=47, help_text='elevator maximal stop'),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='range_min_floor',
            field=models.SmallIntegerField(default=0, help_text='elevator minimal start'),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='set_lobby_floor',
            field=models.SmallIntegerField(default=0, help_text='extra - elevator lobby floor - allow elevator go to lobby or not if min floor > 0'),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='speed_close',
            field=models.DecimalField(decimal_places=2, default=3.7, help_text='in simili seconds, closing door', max_digits=2),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='speed_floor',
            field=models.DecimalField(decimal_places=2, default=2.1, help_text='in simili seconds, elevator travel one floor', max_digits=2),
        ),
        migrations.AlterField(
            model_name='buildingelevator',
            name='speed_open',
            field=models.DecimalField(decimal_places=2, default=8.4, help_text='in simili seconds, opening door + people goes out/in', max_digits=2),
        ),
    ]
