# Generated by Django 3.2.3 on 2021-05-21 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorq', '0006_auto_20210521_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingelevator',
            old_name='set_lobby_floor',
            new_name='lobby_floor',
        ),
    ]
