# Generated by Django 3.2.3 on 2021-05-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevatorq', '0007_rename_set_lobby_floor_buildingelevator_lobby_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingelevator',
            name='current_direction',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('IDLE', 'Idle')], default='IDLE', max_length=4),
        ),
        migrations.AlterField(
            model_name='elevatorq',
            name='direction',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down'), ('IDLE', 'Idle')], default='IDLE', max_length=4),
        ),
        migrations.AlterField(
            model_name='pressbtnq',
            name='direction',
            field=models.CharField(choices=[('UP', 'Up'), ('DOWN', 'Down')], default='UP', max_length=4),
        ),
        migrations.AlterField(
            model_name='pressbtnq',
            name='final_floor',
            field=models.SmallIntegerField(help_text='floor between min 0 and max 47 depends on your direction'),
        ),
        migrations.AlterField(
            model_name='pressbtnq',
            name='start_floor',
            field=models.SmallIntegerField(help_text='floor between min 0 and max 47 depends on your direction'),
        ),
    ]
